# SAP Landscape Inventory

[hana_primary]
sapns2s4npdb   sid=S41   instance=00

[hana_secondary]
sapns2s4nphdb  sid=S41   instance=00

[ascs]
sapns2s4npscs  sid=S41   instance=01

[ers]
sapns2s4npers  sid=S41   instance=11

[app_servers]
sapns2s4npas1  sid=S41   instance=00
sapns2s4npas2  sid=S41   instance=00

[all_hana:children]
hana_primary
hana_secondary

[all_sap:children]
hana_primary
hana_secondary
ascs
ers
app_servers

[all_sap:vars]
ansible_user                 = I560410
ansible_ssh_private_key_file = ~/.ssh/id_rsa
ansible_python_interpreter   = /usr/bin/python3
